### ISSUE TITLE
php74 swoole扩展中无法开启 http2 

### ISSUE THREAD

**Issue by fengjieyunyuan** [garymengcom/dnmp#547]
php74 swoole扩展中无法开启 http2 只能开启openssl；可能是 installExtensionFromTgz() 方法的问题

修改后的方法
installExtensionFromTgz()
{
    tgzName=$1
    para1= 
    extensionName="${tgzName%%-*}"
    ####增加了一个 [] 参数传入进去了，但是无法开启对应的参数选选项了 
   ###例如 ： installExtensionFromTgz swoole-4.8.12 "--enable-openssl --enable-http2 --enable-sockets --enable-mysqlnd --enable-swoole-curl --enable-cares" 直接导致所有的选项都不可用

    if [[  $2 ]]; then  
        para1=$2
    fi  
   ......
}

**Comment by jingmian** [comment]
已修正，再测试试试

**Comment by fengjieyunyuan** [comment]
ok
